[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Add this environment block below
[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
